import { DOkemonType, MoveCategory, Move } from "./types";

export const MOVE_POOL: Move[] = [
  // ── FIRE ──
  {
    id: "ember",
    name: "EMBER",
    type: DOkemonType.FIRE,
    category: MoveCategory.SPECIAL,
    power: 40,
    pp: 30,
    accuracy: 100,
    effects: [{ kind: "burn", chance: 0.1 }],
    description: "A small flame attack. May burn.",
  },
  {
    id: "fire_fang",
    name: "FIRE FANG",
    type: DOkemonType.FIRE,
    category: MoveCategory.PHYSICAL,
    power: 65,
    pp: 20,
    accuracy: 95,
    effects: [{ kind: "burn", chance: 0.1 }],
    description: "A fiery bite. May burn.",
  },
  {
    id: "inferno",
    name: "INFERNO",
    type: DOkemonType.FIRE,
    category: MoveCategory.SPECIAL,
    power: 90,
    pp: 10,
    accuracy: 85,
    effects: [{ kind: "burn", chance: 0.3 }],
    description: "An intense blast of fire. May burn.",
  },

  // ── WATER ──
  {
    id: "aqua_jet",
    name: "AQUA JET",
    type: DOkemonType.WATER,
    category: MoveCategory.PHYSICAL,
    power: 40,
    pp: 25,
    accuracy: 100,
    effects: [{ kind: "priority", value: 1 }],
    description: "A quick water strike. Always goes first.",
  },
  {
    id: "water_pulse",
    name: "WATER PULSE",
    type: DOkemonType.WATER,
    category: MoveCategory.SPECIAL,
    power: 60,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "none" }],
    description: "A pulsing wave of water.",
  },
  {
    id: "tidal_wave",
    name: "TIDAL WAVE",
    type: DOkemonType.WATER,
    category: MoveCategory.SPECIAL,
    power: 85,
    pp: 10,
    accuracy: 90,
    effects: [{ kind: "none" }],
    description: "A massive wave crashes down.",
  },

  // ── PLANT ──
  {
    id: "vine_lash",
    name: "VINE LASH",
    type: DOkemonType.PLANT,
    category: MoveCategory.PHYSICAL,
    power: 60,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "none" }],
    description: "Strikes with sharp vines.",
  },
  {
    id: "razor_leaf",
    name: "RAZOR LEAF",
    type: DOkemonType.PLANT,
    category: MoveCategory.PHYSICAL,
    power: 55,
    pp: 25,
    accuracy: 95,
    effects: [{ kind: "none" }], // high crit handled in engine
    description: "Sharp leaves slice the foe.",
  },
  {
    id: "spore_cloud",
    name: "SPORE CLOUD",
    type: DOkemonType.PLANT,
    category: MoveCategory.STATUS,
    power: 0,
    pp: 15,
    accuracy: 75,
    effects: [{ kind: "sleep" }],
    description: "Releases sleep-inducing spores.",
  },
  {
    id: "solar_beam",
    name: "SOLAR BEAM",
    type: DOkemonType.PLANT,
    category: MoveCategory.SPECIAL,
    power: 90,
    pp: 10,
    accuracy: 90,
    effects: [{ kind: "none" }],
    description: "A concentrated beam of sunlight.",
  },

  // ── SPARK ──
  {
    id: "bolt",
    name: "BOLT",
    type: DOkemonType.SPARK,
    category: MoveCategory.SPECIAL,
    power: 70,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "paralyze", chance: 0.1 }],
    description: "A bolt of lightning. May paralyze.",
  },
  {
    id: "spark_fang",
    name: "SPARK FANG",
    type: DOkemonType.SPARK,
    category: MoveCategory.PHYSICAL,
    power: 65,
    pp: 20,
    accuracy: 95,
    effects: [{ kind: "paralyze", chance: 0.1 }],
    description: "An electric bite. May paralyze.",
  },
  {
    id: "thunder",
    name: "THUNDER",
    type: DOkemonType.SPARK,
    category: MoveCategory.SPECIAL,
    power: 95,
    pp: 8,
    accuracy: 75,
    effects: [{ kind: "paralyze", chance: 0.3 }],
    description: "A devastating thunderbolt. May paralyze.",
  },

  // ── STONE ──
  {
    id: "rock_throw",
    name: "ROCK THROW",
    type: DOkemonType.STONE,
    category: MoveCategory.PHYSICAL,
    power: 50,
    pp: 25,
    accuracy: 90,
    effects: [{ kind: "none" }],
    description: "Hurls a boulder at the foe.",
  },
  {
    id: "stone_edge",
    name: "STONE EDGE",
    type: DOkemonType.STONE,
    category: MoveCategory.PHYSICAL,
    power: 80,
    pp: 10,
    accuracy: 80,
    effects: [{ kind: "none" }],
    description: "Sharp stones strike from below.",
  },
  {
    id: "earthquake",
    name: "EARTHQUAKE",
    type: DOkemonType.STONE,
    category: MoveCategory.PHYSICAL,
    power: 85,
    pp: 10,
    accuracy: 100,
    effects: [{ kind: "none" }],
    description: "The ground shakes violently.",
  },

  // ── METAL ──
  {
    id: "iron_bash",
    name: "IRON BASH",
    type: DOkemonType.METAL,
    category: MoveCategory.PHYSICAL,
    power: 60,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "none" }],
    description: "Strikes with a metallic body.",
  },
  {
    id: "steel_lance",
    name: "STEEL LANCE",
    type: DOkemonType.METAL,
    category: MoveCategory.PHYSICAL,
    power: 80,
    pp: 15,
    accuracy: 90,
    effects: [{ kind: "none" }],
    description: "A piercing lance of steel.",
  },
  {
    id: "iron_wall",
    name: "IRON WALL",
    type: DOkemonType.METAL,
    category: MoveCategory.STATUS,
    power: 0,
    pp: 20,
    accuracy: 0,
    effects: [{ kind: "stat_up", stat: "def", stages: 2 }],
    description: "Hardens the body to boost defense.",
  },

  // ── SPIRIT ──
  {
    id: "shadow_bolt",
    name: "SHADOW BOLT",
    type: DOkemonType.SPIRIT,
    category: MoveCategory.SPECIAL,
    power: 65,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "none" }],
    description: "A bolt of ghostly energy.",
  },
  {
    id: "nightmare",
    name: "NIGHTMARE",
    type: DOkemonType.SPIRIT,
    category: MoveCategory.SPECIAL,
    power: 85,
    pp: 10,
    accuracy: 90,
    effects: [{ kind: "none" }],
    description: "Haunts the foe with dark visions.",
  },
  {
    id: "hex",
    name: "HEX",
    type: DOkemonType.SPIRIT,
    category: MoveCategory.SPECIAL,
    power: 50,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "none" }], // doubles power if target has status (handled in engine)
    description: "Power doubles if foe has a status.",
  },

  // ── VENOM ──
  {
    id: "acid_spray",
    name: "ACID SPRAY",
    type: DOkemonType.VENOM,
    category: MoveCategory.SPECIAL,
    power: 40,
    pp: 25,
    accuracy: 100,
    effects: [{ kind: "stat_down", stat: "spc", stages: 1 }],
    description: "Sprays acid. Lowers foe's Special.",
  },
  {
    id: "poison_fang",
    name: "POISON FANG",
    type: DOkemonType.VENOM,
    category: MoveCategory.PHYSICAL,
    power: 55,
    pp: 20,
    accuracy: 100,
    effects: [{ kind: "poison", chance: 0.3 }],
    description: "A venomous bite. May poison.",
  },
  {
    id: "toxic",
    name: "TOXIC",
    type: DOkemonType.VENOM,
    category: MoveCategory.STATUS,
    power: 0,
    pp: 15,
    accuracy: 85,
    effects: [{ kind: "poison", chance: 1.0 }],
    description: "Badly poisons the foe.",
  },
  {
    id: "sludge_bomb",
    name: "SLUDGE BOMB",
    type: DOkemonType.VENOM,
    category: MoveCategory.SPECIAL,
    power: 80,
    pp: 12,
    accuracy: 90,
    effects: [{ kind: "poison", chance: 0.2 }],
    description: "Hurls toxic sludge. May poison.",
  },

  // ── NEUTRAL ──
  {
    id: "tackle",
    name: "TACKLE",
    type: "NEUTRAL",
    category: MoveCategory.PHYSICAL,
    power: 40,
    pp: 35,
    accuracy: 100,
    effects: [{ kind: "none" }],
    description: "A basic physical attack.",
  },
  {
    id: "slam",
    name: "SLAM",
    type: "NEUTRAL",
    category: MoveCategory.PHYSICAL,
    power: 70,
    pp: 15,
    accuracy: 90,
    effects: [{ kind: "none" }],
    description: "Slams the foe with great force.",
  },
  {
    id: "rest",
    name: "REST",
    type: "NEUTRAL",
    category: MoveCategory.STATUS,
    power: 0,
    pp: 10,
    accuracy: 0,
    effects: [{ kind: "heal_self" }, { kind: "sleep" }],
    description: "Fully heals HP but falls asleep for 2 turns.",
  },
  {
    id: "harden",
    name: "HARDEN",
    type: "NEUTRAL",
    category: MoveCategory.STATUS,
    power: 0,
    pp: 30,
    accuracy: 0,
    effects: [{ kind: "stat_up", stat: "def", stages: 1 }],
    description: "Hardens the body to raise Defense.",
  },
  {
    id: "growl",
    name: "GROWL",
    type: "NEUTRAL",
    category: MoveCategory.STATUS,
    power: 0,
    pp: 30,
    accuracy: 100,
    effects: [{ kind: "stat_down", stat: "atk", stages: 1 }],
    description: "Growls to lower the foe's Attack.",
  },
  {
    id: "quick_attack",
    name: "QUICK ATK",
    type: "NEUTRAL",
    category: MoveCategory.PHYSICAL,
    power: 40,
    pp: 30,
    accuracy: 100,
    effects: [{ kind: "priority", value: 1 }],
    description: "A fast strike. Always goes first.",
  },
];

export const MOVE_MAP = new Map(MOVE_POOL.map((m) => [m.id, m]));

export function getMoveById(id: string): Move {
  const move = MOVE_MAP.get(id);
  if (!move) throw new Error(`Unknown move: ${id}`);
  return move;
}
